### ISSUE TITLE
Implement relaton-jis

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-jis#1]
JIS are Japanese Industrial Standards and are found on these two places:

* JISC: https://www.jisc.go.jp/app/jis/general/GnrJISSearch.html (the first box for document identifier)
<img width="801" alt="Screenshot 2023-03-06 at 5 10 56 PM" src="https://user-images.githubusercontent.com/11865/223066153-cabf3cd7-1d56-4ef3-acce-7f65f7261cea.png">

* JSA group https://webdesk.jsa.or.jp (select first item)
<img width="613" alt="Screenshot 2023-03-06 at 5 11 37 PM" src="https://user-images.githubusercontent.com/11865/223066328-e2d823c6-3fbc-41ac-a3ad-8b921b4b9d9c.png">

or https://webdesk.jsa.or.jp/books/W11M0270 for the full form
<img width="909" alt="Screenshot 2023-03-06 at 5 12 11 PM" src="https://user-images.githubusercontent.com/11865/223066451-b362f3e5-1fbb-4578-b800-e8044c7783f9.png">

The text means:
* 規格番号 the standard identifer
* 標題 title
* ICS: ICS codes
* 発行年月日: date of publication
* 関連規格 (related standards): 3 values: [cites JIS standard; cites international standard; corresponds to international standard]

<img width="756" alt="Screenshot 2023-03-06 at 5 13 09 PM" src="https://user-images.githubusercontent.com/11865/223066689-707636c3-e91e-4df9-b05b-53f6e6a04398.png">

* 状態 (status): 有効 (effective) 廃止 (retracted/withdrawn)

**Comment by andrew2net** [comment]
@ronaldtse implemented. The gems `relaton` -v 1.15.2 and `relaton-cli` -v 1.15.1 support it now. I'm not sure what doctype should we use for the JIS documents.
```
relaton fetch 'JIS X 0208'
[relaton-jis] ("JIS X 0208") fetching...
[relaton-iso-bib] WARNING: invalid doctype: standard
[relaton-iso-bib] Allowed doctypes are: international-standard, technical-specification, technical-report, publicly-available-specification, international-workshop-agreement, guide, amendment, technical-corrigendum, directive
[relaton-jis] ("JIS X 0208") found JIS X 0208:1997
[relaton-iso-bib] WARNING: invalid doctype: standard
[relaton-iso-bib] Allowed doctypes are: international-standard, technical-specification, technical-report, publicly-available-specification, international-workshop-agreement, guide, amendment, technical-corrigendum, directive
<bibdata type="standard" schema-version="v1.2.1">
  <fetched>2023-03-21</fetched>
  <title format="text/plain" language="ja" script="Jpan">７ビット及び８ビットの２バイト情報交換用符号化漢字集合</title>
  <title format="text/plain" language="en" script="Lant">7-bit and 8-bit double byte coded KANJI sets for information interchange</title>
  <uri type="src">https://webdesk.jsa.or.jp/books/W11M0090/index/?bunsyo_id=JIS+X+0208%3A1997</uri>
  <uri type="pdf">https://webdesk.jsa.or.jp/preview/pre_jis_x_00208_000_000_1997_j_pr11_i4.pdf</uri>
  <docidentifier type="JIS" primary="true">JIS X 0208:1997</docidentifier>
  <docnumber>X0208</docnumber>
  <date type="issued">
    <on>1997-02-28</on>
  </date>
  <date type="confirmed">
    <on>2007-09-20</on>
  </date>
  <contributor>
    <role type="author"/>
    <organization>
      <name language="ja" script="Jpan">一般財団法人　日本規格協会</name>
    </organization>
  </contributor>
  <language>ja</language>
  <script>Jpan</script>
  <abstract format="text/plain" language="ja" script="Jpan">６８７９文字の図形文字とそれらのビット組合せとの対応を規定。符号化漢字集合は，この規格で規定する漢字集合だけを利用する場合，又はＪＩＳ　Ｘ　０２０１のラテン文字用図形文字集合若しくはＩＳＯ／ＩＥＣ　６４６の国際基準版（ＩＲＶ）と組み合わせて利用する場合，それぞれについての７ビット・８ビットの２バイト符号について適用。</abstract>
  <status>
    <stage>valid</stage>
  </status>
  <ext schema-version="">
    <doctype>standard</doctype>
    <editorialgroup>
      <technical-committee>一般財団法人　日本規格協会</technical-committee>
    </editorialgroup>
    <ics>
      <code>35.040</code>
      <text>Information coding</text>
    </ics>
    <structuredidentifier type="JIS">
      <docnumber/>
    </structuredidentifier>
  </ext>
</bibdata>
```

**Comment by ronaldtse** [comment]
Thank you!

There are 4 types of documents:
* `japanese-industrial-standard`
* `technical-report`
* `technical-specification`
* `amendment`

**Comment by ronaldtse** [comment]
@andrew2net is this done? Also, pubid-jis is now ready for use. If so let's close this.

**Comment by andrew2net** [comment]
@ronaldtse just need to update doctypes
