### ISSUE TITLE
(URGENT) Failure to retrieve `JIS B 0060(規格群)`

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-jis#10]
```
[relaton-jis] (JIS B 0060(規格群)) Fetching from webdesk.jsa.or.jp ...
[relaton-jis] (JIS B 0060(規格群)) Not found.
```

**Comment by andrew2net** [comment]
@ronaldtse `JIS B 0060(規格群)`, `JIS B 0060 (規格群)`, or `JIS B 0060 規格群` references are not searchable on the webdesk.jsa.or.jp

<img width="450" alt="image" src="https://github.com/relaton/relaton-jis/assets/5623890/67acbd02-71c9-41bb-94a5-c619f1011a74">

"Keyword searches that include half-width symbols are not possible."
The `JIS B 0060` returns document
```sh
$ relaton fetch 'JIS B 0060'
[relaton-jis] (JIS B 0060) Fetching from webdesk.jsa.or.jp ...
[relaton-jis] (JIS B 0060) Found: `JIS B 0060-10`
<bibdata type="standard" schema-version="v1.2.5">
...
```

**Comment by ronaldtse** [comment]
` (規格群)` means "all parts". Don't we have support for "all parts"?

**Comment by andrew2net** [comment]
> ` (規格群)` means "all parts". Don't we have support for "all parts"?

@ronaldtse sorry, I forgot that "all parts" can be in Japanese. Yes, we have support for "all parts", but a space should present between number and the "all parts" option:
```sh
relaton fetch 'JIS B 0060 (規格群)'
[relaton-jis] (JIS B 0060 (規格群)) Fetching from webdesk.jsa.or.jp ...
[relaton-jis] (JIS B 0060 (規格群)) Found: `JIS B 0060 (all parts)`
<bibdata type="standard" schema-version="v1.2.5">
...
```

**Comment by ronaldtse** [comment]
@andrew2net can you please help update the README to indicate how to use this? Thanks!

**Comment by ronaldtse** [comment]
Confirm this is fixed. Thank you @andrew2net !

**Comment by opoudjis** [comment]
A reminder.

The  metalanguage of Metanorma is English. If there are directives in Metanorma, including directives to be passed on to Relaton, they are going to be in English. That includes recognition of section titles (as we've just seen in ISO/IEC 2382). And it applies just as much here.

I am NOT going to recognise the "all parts" string in Japanese, French, Russian, or Klingon. Inasmuch as I part "all parts" as a part of a citation (and I do), I am only going to recognise it once, in English. Just as I recognise clause title type only by the value of the title string, or else the heading attribute, in English.

The request to recognise  `JIS B 0060(規格群)` should not be coming from Metanorma. Metanorma should only present `JIS B 0060 (all parts)`, for consistency. If @andrew2net needs to translate that into a search for  `JIS B 0060(規格群)` on the JIS website, that's fine, but recognising different languages in markup is an unreasonable added burden.

**Comment by ronaldtse** [comment]
@opoudjis There is a growing need in authoring standards in different languages, and it is up to our strategy to whether allow that or not. "Control languages" like `[options...]` or `[strikethrough]` is fine in English.

However, presentational things like `Scope` or `(all parts)` should be subject to internationalization.

> translate that into a search for  JIS B 0060(規格群) on the JIS website

No, there is no such thing. Just like "ISO 9000 (all parts)" does not exist on ISO's website. It is Relaton that creates the bibliographic series for citation.

**Comment by opoudjis** [comment]
I'm disagreeing with you that "Scope" and "(all parts)" here are presentation. To me, they are part of the control language; and they are already being internationalised in presentation.
