### ISSUE TITLE
(URGENT) Crash in fetching withdrawn standards, e.g. `JIS Z 8201`, `JIS Z 8202`

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-jis#11]
```
[relaton] ERROR: `JIS Z 8201` -- undefined method `fetch' for nil:NilClass

      item = hits.max_by { |i| i.id_parts[:year].to_i }.fetch
                                                       ^^^^^^
```

**Comment by ronaldtse** [comment]
Seems that it happens for others too:

```
[relaton] ERROR: `JIS Z 8202` -- undefined method `fetch' for nil:NilClass

      item = hits.max_by { |i| i.id_parts[:year].to_i }.fetch
                                                       ^^^^^^
[relaton-jis] (JIS Z 8301) Fetching from webdesk.jsa.or.jp ...
[relaton] ERROR: `JIS Z 8203` -- undefined method `fetch' for nil:NilClass

      item = hits.max_by { |i| i.id_parts[:year].to_i }.fetch
                                                       ^^^^^^
```

**Comment by ronaldtse** [comment]
@andrew2net the problem is that if you do the normal search, there will be 0 results, because this standard has been withdrawn.
<img width="1082" alt="Screenshot 2023-11-22 at 12 14 59 AM" src="https://github.com/relaton/relaton-jis/assets/11865/0dd00602-999d-4403-9ee3-eb23c5ef04d8">

You need to use the "Advanced Search" form with a ticked "withdrawn" button in order to find the entry:
<img width="813" alt="Screenshot 2023-11-22 at 12 15 08 AM" src="https://github.com/relaton/relaton-jis/assets/11865/89a6bfb2-44f2-4ef8-81af-1d9d77f964fa">

**Comment by andrew2net** [comment]
Fixed in v1.16.4
```sh
$ relaton fetch 'JIS Z 8201'            
[relaton-jis] (JIS Z 8201) Fetching from webdesk.jsa.or.jp ...
[relaton-jis] (JIS Z 8201) Found: `JIS Z 8201`
<bibdata type="standard" schema-version="v1.2.5">
...

$ relaton fetch 'JIS Z 8202'
[relaton-jis] (JIS Z 8202) Fetching from webdesk.jsa.or.jp ...
[relaton-jis] (JIS Z 8202) Found: `JIS Z 8202-0`
<bibdata type="standard" schema-version="v1.2.5">
...

$ relaton fetch 'JIS Z 8301'
[relaton-jis] (JIS Z 8301) Fetching from webdesk.jsa.or.jp ...
[relaton-jis] (JIS Z 8301) Found: `JIS Z 8301`
<bibdata type="standard" schema-version="v1.2.5">
...
```

**Comment by ronaldtse** [comment]
@andrew2net can I also confirm that with this fix we can retrieve TR documents? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse do you mean docs like `TR A 0001:1996`? No, this fix didn't add the TR supporting. The Advanced Search finds the TR documents but It needs to add TR prefix and update ID/reference parser. Will do it.

**Comment by ronaldtse** [comment]
@andrew2net can you try creating pubid-jis with the same interface as other pubid gems? I think this will improve progress and also the quality of pubid gems in general.

**Comment by andrew2net** [comment]
@ronaldtse I can try.

**Comment by andrew2net** [comment]
@ronaldtse TR supporting is added in v1.16.8
```sh
$ relaton fetch 'TR A 0001:1996'
Resolving dependencies...
/Users/andrej/.rvm/gems/ruby-3.2.0/gems/relaton-jis-1.16.8/lib/relaton_jis/version.rb:4: warning: already initialized constant RelatonJis::VERSION
/Users/andrej/RubyProjects/relaton-jis/lib/relaton_jis/version.rb:4: warning: previous definition of VERSION was here
[relaton-jis] (TR A 0001:1996) Fetching from webdesk.jsa.or.jp ...
[relaton-jis] (TR A 0001:1996) Found: `TR A 0001:1996`
<bibdata type="standard" schema-version="v1.2.5">
...
```

**Comment by andrew2net** [comment]
> @andrew2net can you try creating pubid-jis with the same interface as other pubid gems? I think this will improve progress and also the quality of pubid gems in general.

@ronaldtse but we already have pubid-jis https://github.com/metanorma/pubid-jis
