### ISSUE TITLE
Create relaton-data-jis dataset

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-jis#12]
On this page: https://webdesk.jsa.or.jp/books/W11M0270
<img width="793" alt="Screenshot 2023-11-22 at 12 19 17 AM" src="https://github.com/relaton/relaton-jis/assets/11865/7e80f9ac-3935-445a-873b-b9527efc34f6">

If you keep the search fields empty, you can get all the results (withdrawn and active standards):
<img width="1063" alt="Screenshot 2023-11-22 at 12 19 50 AM" src="https://github.com/relaton/relaton-jis/assets/11865/07c1fa47-45a5-44ff-8e51-7701575c6c09">

Then for every item, you can see the details of the standard.
<img width="1059" alt="Screenshot 2023-11-22 at 12 20 36 AM" src="https://github.com/relaton/relaton-jis/assets/11865/1ae19e74-f5f7-4bf5-873c-29ec727a8194">
<img width="1068" alt="Screenshot 2023-11-22 at 12 20 42 AM" src="https://github.com/relaton/relaton-jis/assets/11865/95723fec-b5f8-4dd7-8aef-20ad7885b230">

**Comment by andrew2net** [comment]
@ronaldtse FYI JIS docs have some ICSs that isoics gem doesn't
```
[isoics] code "91.140.20" not found in ICS list
[isoics] code "59.080.60" not found in ICS list
[isoics] code "91.100.20" not found in ICS list
[isoics] code "35.260.10" not found in ICS list
[isoics] code "31.160.50" not found in ICS list
[isoics] code "13.220.60" not found in ICS list
[isoics] code "35.260.20" not found in ICS list
[isoics] code "49.040.40" not found in ICS list
```

**Comment by ronaldtse** [comment]
Can we find out the details of those codes? I know that CEN also has additional codes not from ISOICS. We need to collect them somehow.

**Comment by andrew2net** [comment]
@ronaldtse found this:

91.140.20 [Heating appliances](https://www.en-standard.eu/ics-codes/91-construction-materials-and-building/91-140-installations-in-buildings/91-140-20-heating-appliances/?srsltid=AfmBOoog0YAicqdduGrpBLkSF3w8pG2SweWPpIqbt8mVaFko0646HyI5)
59.080.60 [Textile floor coverings](https://www.en-standard.eu/ics-codes/59-textile-and-leather-technology/59-080-products-of-the-textile-industry/59-080-60-textile-floor-coverings/)
91.100.20 [Mineral and ceramic materials and products](https://www.en-standard.eu/ics-codes/91-construction-materials-and-building/91-100-construction-materials/91-100-20-mineral-and-ceramic-materials-and-products/?srsltid=AfmBOorBC8l2fcIgYnKiCRYh5B5E3Kgg4Ndsg9D8qilaZ0YlkT31segr)
35.260.10 [Office machines](https://www.en-standard.eu/ics-codes/35-information-technology-office-machines/35-260-office-machines/35-260-10-office-machines/?srsltid=AfmBOooynqpieTQYyRB_vAQ5pO5Eu6SpqQQME-WA5E9OCOOkC6xnLhX9)
31.160 [Electric filters](https://www.en-standard.eu/ics-codes/31-electronics/31-160-electric-filters/)
31.160.50 ?
13.220 [Protection against fire](https://www.en-standard.eu/ics-codes/13-environment-health-protection-safety/13-220-protection-against-fire/)
13.220.60 ?
35.260.20 [Stationery](https://www.en-standard.eu/ics-codes/35-information-technology-office-machines/35-260-office-machines/35-260-20-stationery/?srsltid=AfmBOooK6ZaLgYgQNrQOyjvGyuA4HwFVdtZvpcEJciTRlmX9HZRyEIA-)
49.040.40 [Coastings and processes](https://www.en-standard.eu/ics-codes/49-aircraft-and-space-vehicle-engineering/49-040-coatings-and-related-processes-used-in-aerospace-industry/49-040-40-coastings-and-processes/?srsltid=AfmBOooASSMCCV6fEwsLQQDjc5H7_eOW1_BMd0wqUZNitjWm2OE8ptf5)
