### ISSUE TITLE
JSA as authorizer in all JIS records

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-jis#17]
In metanorma-jis https://github.com/metanorma/mn-samples-jis/issues/47 , I need to know whether a standard is a JIS standard or not, in order to decide how to render it: a JIS standard is rendered in the bibliography with just its title, as is the case for ISO and IEC, whereas a standard by an outside body is rendered with more bibliographic information—publisher, URL, date, etc.

Now, I have until now been using the publisher name to decide whether a standard belongs to JIS or not:

JIS B 0001 for example has the publisher:

````
<contributor>
    <role type="publisher"/>
    <organization>
<name language="ja" script="Jpan">一般財団法人　日本規格協会</name>
   </organization>
  </contributor>
````

"General incorporated foundation: Japanese Standards Association".

However, JIS P 0138 is *not* published by the Japanese Standards Association. It is published instead by the Japanese Paper Manufacturer's Association:

````
  <contributor>
    <role type="author"/>
    <organization> 
<name language="ja" script="Jpan">日本製紙連合会</name>
    </organization>
  </contributor>
````

As a result, I do not recognise it as a JIS standard.

In order to deal with a potentially large number of random Japanese industrial associations as publishers, I request that we add the Japanese Standards Association as an "authorizer" of JIS standards. That is what an authorizer means: it's the authoritative body lending its authority to the publication.

So I request that you add, to every single JIS record, the contributor:

````
<contributor>
    <role type="authorizer"/>
    <organization>
<name language="ja" script="Jpan">一般財団法人　日本規格協会</name>
   </organization>
  </contributor>
````

And I will use that field to identify the publication as belonging to JIS.

(I do not wish to use the identifier prefix: we have no guarantee that JSA publications will always use the same prefix, and that is not a semantically transparent choice.)

**Comment by andrew2net** [comment]
@opoudjis can't `docidentifier[@type]` be used to detect if a standard is JIS?
```xml
<bibdata type="standard" schema-version="v1.2.9">
  ...
  <docidentifier type="JIS" primary="true">JIS P 0138</docidentifier>
  ...
```

**Comment by opoudjis** [comment]
I don't trust that all JSA publications will have a document identifier of type JIS. We've both been involved in this long enough to know that identifies change prefixes for all sorts of Random administrative reasons.

@ronaldtse Has said he will look at this, but I need a consistent organisation With a consistent role for These documents.

**Comment by andrew2net** [comment]
@opoudjis the `docidentifier[@type]` is hardcoded in relaton-jis, and it's always `JIS`. Should we parse IDs' prefixes to create different types? If not then type can be used to detect JIS standards.

**Comment by opoudjis** [comment]
I do not want to trust the document identifier prefix, it's simply too variable and not semantically based in the general case, and we have seen it blow up in flavours like NIST. I would have far more confidence in an organisation like JSA being acknowledged in the metadata.

@ronaldtse Still need this looked at.

**Comment by ronaldtse** [comment]
There are other identifiers with different prefixes like "JSA" but remember, JIS standards quote home standards with "JIS prefix". So maybe no need to consider "home standard" here.

**Comment by opoudjis** [comment]
... So you want me to use document identifier prefix as the criterion after all?

... Are you sure?

**Comment by ronaldtse** [comment]
Perhaps the better way to ask is:
* what SDOs distinguish home identifiers and foreign identifiers?

IETF, NIST and...?

Because ISO, IHO, OGC, etc all use the full identifier in their own publications.

**Comment by opoudjis** [comment]
> Perhaps the better way to ask is:
> 
> * what SDOs distinguish home identifiers and foreign identifiers?
> 
> IETF, NIST and...?
> 
> Because ISO, IHO, OGC, etc all use the full identifier in their own publications.


You've misunderstood the notion of a home standard. I never spoke of home identifiers, that's something you're misconstruing here. This has absolutely nothing whatsoever to do with NIST and BSI omitting the SDO prefix before their identifiers.

ISO give only the title for ISO and IEC standards in citation, and no other information. That is what a home standard is: an in-house standard is cited with minimal bibliographic information, compared to an external standard.

SImilar things happen with all of BIPM, BSI, IEC, IEE, IETF, and JIS. And I suspect that for the others, we don't have it for lack of being told about it: only NIST and OGC cite their in-house standards bibliographically like they do any other standard.

**Comment by andrew2net** [comment]
fixed in v 1.19.3

**Comment by ronaldtse** [comment]
@opoudjis indeed, and actually you should document "what a home standard is and how it affects bibliographic rendering" on metanorma.org. For sure this is of interest to people who wish to develop new flavors and bibliographic practices.

**Comment by opoudjis** [comment]
I'm not sure if it belongs on metanorma.org, being an attribute of relaton-render, but it belongs there more than relaton.org. It isn't documented in relaton-render either currently, because it is a flavour-specific addition. It's pervasive enough though it that it needs to be. Will document, and will move relaton-render readme to developer branch of metanorma.org

**Comment by ronaldtse** [comment]
@opoudjis should bibliography/citation rendering be in the domain of Relaton? Maybe that's the right place to be, since it is 690 related.
