### ISSUE TITLE
Behave like relaton-iso for undated citations

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-jis#6]
Right now a query for `JIS B 0001` is returning the entry for `JIS B 0001:2019`. relaton-jis needs to behave like relaton-iso: if the citation is undated, it needs to return the citation without the year, and with the year-specific record added on as an instance.

**Comment by opoudjis** [comment]
Is blocking https://github.com/metanorma/metanorma-jis/issues/23

**Comment by andrew2net** [comment]
Implemented in v 1.14.2
https://github.com/relaton/relaton-jis/blob/main/spec/fixtures/jis_x_0208.xml
